version: "3.8"

services:
  reth:
    image: '${RETH_IMAGE}'
    pull_policy: always
    container_name: reth
    restart: unless-stopped
    stop_signal: SIGINT
    stop_grace_period: 2m
    ports:
    - 30303:30303
    - 30303:30303/udp
    - 8545:8545
    - 8546:8546
    - 8551:8551
    volumes:
    - /data/reth:/data
    command:
    - node
    - --chain=${NETWORK}
    - --datadir=/data
    - --peers-file=/data/peers.file
    - --nat=extip:${PUBLIC_IP}
    - --port=30303
    - --http
    - --http.addr=0.0.0.0
    - --http.api=eth,net,web3,admin
    - --http.corsdomain=*
    - --ws
    - --ws.origins=*
    - --ws.addr=0.0.0.0
    - --ws.api=eth,net,web3
    - --authrpc.addr=0.0.0.0
    - --authrpc.jwtsecret=/data/jwt.hex
    - --authrpc.port=8551
  teku:
    image: '${TEKU_IMAGE}'
    pull_policy: always
    container_name: teku
    restart: unless-stopped
    stop_grace_period: 2m
    volumes:
    - /data/teku:/data
    - /data/reth:/reth
    ports:
    - 8080:8080
    - ${P2P_PORT}:${P2P_PORT}
    - ${P2P_PORT}:${P2P_PORT}/udp
    command:
    - /opt/teku/bin/teku
    - --network=${NETWORK}
    - --data-path=/data
    - --data-beacon-path=/data/beacon
    - --data-storage-archive-frequency=${ARCHIVE_FREQUENCY}
    - --data-storage-mode=${STORAGE_MODE}
    - --Xdata-storage-archive-finalized-states-retained=${RETAINED_SLOT}
    - --ee-endpoint=http://reth:8551
    - --ee-jwt-secret-file=/reth/jwt.hex
    - --p2p-enabled=true
    - --p2p-advertised-ip=${PUBLIC_IP}
    - --p2p-advertised-port=${P2P_PORT}
    - --rest-api-enabled=true
    - --rest-api-host-allowlist=*
    - --rest-api-interface=0.0.0.0
    - --rest-api-port=8080
    - --rest-api-cors-origins=false

